# Generated by Django 4.1.7 on 2023-05-14 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_prettynum"),
    ]

    operations = [
        migrations.CreateModel(
            name="placeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=20, verbose_name="场所名")),
                ("place_capacity", models.IntegerField(verbose_name="总人数")),
                ("place_occupied", models.IntegerField(verbose_name="已入座人数")),
                (
                    "campus",
                    models.SmallIntegerField(
                        choices=[(1, "江湾校区"), (2, "邯郸校区"), (3, "枫林校区"), (4, "张江校区")],
                        default=1,
                        verbose_name="校区",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="seatInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已预约"), (2, "已上座"), (3, "未使用")],
                        default=3,
                        verbose_name="座位状态",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.placeinfo",
                        verbose_name="场所名",
                    ),
                ),
            ],
        ),
    ]
