# Generated by Django 4.1.7 on 2023-05-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_placeinfo_seatinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="placeinfo",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="闭馆时间"),
        ),
        migrations.AddField(
            model_name="placeinfo",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="开馆时间"),
        ),
    ]
