# Generated by Django 4.1.7 on 2023-05-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_placeinfo_end_time_placeinfo_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatinfo",
            name="reservation_end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="预约的结束时间"),
        ),
        migrations.AddField(
            model_name="seatinfo",
            name="reservation_start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="预约的开始时间"),
        ),
        migrations.CreateModel(
            name="roomInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=20, verbose_name="自习室")),
                ("room_capacity", models.IntegerField(verbose_name="总座位数")),
                ("room_occupied", models.IntegerField(verbose_name="已入座人数")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.placeinfo",
                        verbose_name="所属场所",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="seatinfo",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.roominfo",
                verbose_name="所属自习室",
            ),
        ),
    ]
