# Generated by Django 4.1.7 on 2023-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_seatinfo_reservation_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="userinfo", name="depart",),
        migrations.AlterField(
            model_name="userinfo",
            name="account",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="学号"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="create_time",
            field=models.DateField(verbose_name="注册时间"),
        ),
    ]
