# Generated by Django 4.1.7 on 2023-05-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0007_remove_userinfo_depart_alter_userinfo_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="account",
            field=models.CharField(max_length=18, verbose_name="学号"),
        ),
    ]
