# Generated by Django 4.1.7 on 2023-05-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0008_alter_userinfo_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="reservationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已预约"), (2, "已上座"), (3, "违约")],
                        default=3,
                        verbose_name="预约记录的状态",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.seatinfo",
                        verbose_name="预约的座位",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app01.userinfo",
                        verbose_name="预约的用户",
                    ),
                ),
            ],
        ),
    ]
