# Generated by Django 4.2.1 on 2023-05-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_reservationinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已预约'), (2, '已上座'), (3, '违约'), (4, '已离开或已取消')], default=3, verbose_name='预约记录的状态'),
        ),
    ]
